import java.util.ArrayList;
import java.util.List;

public class Problem2 {

    static public void problem2() {
        //Even Fibonacci numbers
        //Problem 2
        //Each new term in the Fibonacci sequence is generated by adding the previous two terms.
        // By starting with 1 and 2, the first 10 terms will be:
        //
        //1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        //
        //By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


        System.out.println("fibonacci ");
        List<Long> serie = new ArrayList<>();
        serie.add(1L);
        serie.add(2L);

        boolean couldContinue = true;
        int i = 2;

        while (couldContinue) {
            Long value = serie.get(i-1) + serie.get(i-2);

            if (value >= 4000000) {
                couldContinue = false;
            }

            serie.add(value);
            i++;
        }

        long sum = 0;

        for (int j=0; j<serie.size(); j++) {
            if (serie.get(j) % 2 == 0) {
                sum += serie.get(j);
            }
        }

        System.out.print(sum);
    }

}
